default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: dev_db

test:
  <<: *default
  database: dev_db_test
production:
  <<: *default
  database: db_db_production
